In [1]:
import pandas as pd

# Load Dataset
df = pd.read_csv("SampleSuperstore.csv")

# Show first 5 rows
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [5]:
import pandas as pd

# Dataset Information
print("========== DATASET OVERVIEW ==========")
print("Rows & Columns :", df.shape)

print("\n========== COLUMN NAMES ==========")
print(df.columns.tolist())

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

print("\n========== DUPLICATE RECORDS ==========")
print(df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Create Profit Margin Column
df["Profit Margin (%)"] = ((df["Profit"] / df["Sales"]) * 100).round(2)

print("\n========== DATA CLEANED ==========")
print("New Shape :", df.shape)

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== SUMMARY ==========")
display(df.describe())

========== DATASET OVERVIEW ==========
Rows & Columns : (9977, 13)

========== COLUMN NAMES ==========
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit']

========== MISSING VALUES ==========
Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

========== DUPLICATE RECORDS ==========
0

========== DATA CLEANED ==========
New Shape : (9977, 14)

========== FIRST 5 ROWS ==========

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin (%)
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,16.00
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,30.00
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,47.00
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-40.00
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,11.25

========== SUMMARY ==========

,Postal Code,Sales,Quantity,Discount,Profit,Profit Margin (%)
count,9977.000000,9977.000000,9977.000000,9977.000000,9977.00000,9977.000000
mean,55154.964117,230.148902,3.790719,0.156278,28.69013,12.011351
std,32058.266816,623.721409,2.226657,0.206455,234.45784,46.663770
min,1040.000000,0.444000,1.000000,0.000000,-6599.97800,-275.000000
25%,23223.000000,17.300000,2.000000,0.000000,1.72620,7.500000
50%,55901.000000,54.816000,3.000000,0.200000,8.67100,27.000000
75%,90008.000000,209.970000,5.000000,0.200000,29.37200,36.250000
max,99301.000000,22638.480000,14.000000,0.800000,8399.97600,50.000000

In [6]:
df.to_csv("Cleaned_SampleSuperstore.csv", index=False)

print("✅ Cleaned dataset saved successfully.")

✅ Cleaned dataset saved successfully.

In [4]:
print(df.columns.tolist())

['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit']